/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const useHead: typeof import('./src/composables/useHead')['useHead']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly useHead: UnwrapRef<typeof import('./src/composables/useHead')['useHead']>
  }
}
declare module '@vue/runtime-core' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly useHead: UnwrapRef<typeof import('./src/composables/useHead')['useHead']>
  }
}
